projecttour/Models/tour.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tour()
        {
            this.tour_chitiet = new HashSet<tour_chitiet>();
            this.tour_doan = new HashSet<tour_doan>();
        }
    
        public int tour_id { get; set; }
        public string tour_ten { get; set; }
        public string tour_mota { get; set; }
        public int loai_id { get; set; }
        public string block { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_chitiet> tour_chitiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_doan> tour_doan { get; set; }
        public virtual tour_loai tour_loai { get; set; }
    }
}

projecttour/Controllers/toursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projecttour.Models;

namespace projecttour.Controllers
{
    public class toursController : Controller
    {
        private tour_dulichEntities1 db = new tour_dulichEntities1();

        // GET: tours
        public ActionResult Index()
        {
            var tours = db.tours.Include(t => t.tour_loai);
            return View(tours.ToList());
        }

        // GET: tours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour tour = db.tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            // load for dropdown dia diem
            ViewBag.diadiem = db.tour_diadiem
                                .Select(c => new SelectListItem { Value = c.dd_id.ToString(), Text = c.dd_ten + "-" + c.dd_thanhpho })
                                .ToList();
            // load data db.chitiet
            ViewBag.cityoftour = (from ct in db.tour_chitiet
                                 join dd in db.tour_diadiem
                                 on ct.dd_id equals dd.dd_id
                                 where ct.tour_id == id
                                 select new SelectListItem { Value = dd.dd_ten, Text = dd.dd_thanhpho }).ToList() ;

            ViewBag.Costs = from c in db.tour_gia
                            where c.tour_id == id
                            select c;

            return View(tour);
        }
        [HttpPost]
        public ActionResult Details(ICollection<string> listPlaces)
        {
            string[] array = new string[listPlaces.Count];
            listPlaces.CopyTo(array, 0);
            TempData["idplace"] = "<script>alert('"+ array[0] + "');</script>";
            for (int i = 1; i < array.Length; i++)
            {
                tour_chitiet oneTour_chitiet = new tour_chitiet();
                int generateIdTour_chitiet = (from id in db.tour_chitiet select id).Max(e => e.ct_id);
                oneTour_chitiet.ct_id = generateIdTour_chitiet + 1;
                oneTour_chitiet.tour_id = int.Parse(array[0]);
                oneTour_chitiet.dd_id = int.Parse(array[i]);
                //thutu?
                oneTour_chitiet.ct_thutu = 1;
                db.tour_chitiet.Add(oneTour_chitiet);
                db.SaveChanges();
            }

            return RedirectToAction("Details");
        }
        // GET: tours/Create
        public ActionResult Create()
        {
            ViewBag.loai_id = new SelectList(db.tour_loai, "loai_id", "loai_ten");
            ViewBag.diadiem = db.tour_diadiem
                                .Select(c => new SelectListItem { Value = c.dd_id.ToString(), Text = c.dd_ten + "-" + c.dd_thanhpho })
                                .ToList();
            ViewBag.block = new List<SelectListItem>(){ new SelectListItem() {Text="0", Value="0"},new SelectListItem() { Text="1", Value="1"} };
            return View();
        }

        // POST: tours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "tour_ten,tour_mota,loai_id,block")] tour tour, ICollection<string> listPlaces)
        {


            int generateID = 0;
            if(db.tours.ToList().Count > 0)
                generateID = (from id in db.tours select id).Max(e => e.tour_id);
            tour.tour_id = generateID + 1;
            if (ModelState.IsValid)
            {
                db.tours.Add(tour);
                db.SaveChanges();
                /*start add cost for tour */
                /*end*/

                /**/
                string[] array = new string[listPlaces.Count];
                listPlaces.CopyTo(array, 0);
                TempData["idplace"] = "<script>alert('" + array[0] + "');</script>";
                for (int i = 1; i < array.Length; i++)
                {
                    tour_chitiet oneTour_chitiet = new tour_chitiet();
                    int generateIdTour_chitiet = 0;
                    if(db.tour_chitiet.ToList().Count>0) generateIdTour_chitiet =(from id in db.tour_chitiet select id).Max(e => e.ct_id);
                    oneTour_chitiet.ct_id = generateIdTour_chitiet + 1;
                    oneTour_chitiet.tour_id = tour.tour_id;
                    oneTour_chitiet.dd_id = int.Parse(array[i]);
                    //thutu?
                    oneTour_chitiet.ct_thutu = 1;
                    db.tour_chitiet.Add(oneTour_chitiet);
                    db.SaveChanges();
                }
                /**/
                return RedirectToAction("Index");
            }

            ViewBag.loai_id = new SelectList(db.tour_loai, "loai_id", "loai_ten", tour.loai_id);
            return View(tour);
        }

        // GET: tours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour tour = db.tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            ViewBag.loai_id = new SelectList(db.tour_loai, "loai_id", "loai_ten", tour.loai_id);
            return View(tour);
        }

        // POST: tours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "tour_id,tour_ten,tour_mota,loai_id,block")] tour tour)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tour).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.loai_id = new SelectList(db.tour_loai, "loai_id", "loai_ten", tour.loai_id);
            return View(tour);
        }

        // GET: tours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour tour = db.tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: tours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tour tour = db.tours.Find(id);
            db.tours.Remove(tour);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projecttour/Views/tours/Create.cshtml
@model projecttour.Models.tour

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card w-100">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 text-danger text-uppercase">
                    <strong>Thêm Tour</strong>
                </div>

                <div class="col-md-6 text-right">
                    <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" title="Thêm">
                        <span class="fa fa-plus-square"></span>
                    </button>
                    <a href="@Url.Action("Index")" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Thoát">
                        <span class="fa fa-reply"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-block p-3">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tên Tour</label>
                        @Html.EditorFor(model => model.tour_ten, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.tour_ten, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Mô tả</label>
                        @Html.EditorFor(model => model.tour_mota, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.tour_mota, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Trạng thái</label>
                        @Html.DropDownList("block", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.block, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Loại du lịch</label>
                        @Html.DropDownList("loai_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.loai_id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Giá tiền</label>
                        <ul class="list-group ">
                            <input type="text" name="listPlaces" value="0" hidden />
                        </ul>

                        <select class="form-control" id="dropdowndiadiem" name="diadiem">
                            <option value="0" selected>Select a place</option>
                            @foreach (var item in ViewBag.diadiem)
                            {
                                <option value="@item.Value">@item.Text</option>
                            }
                        </select>
                        <button id="addiadiem" type="button" class="btn btn-sm btn-success form-control mt-3" >
                            <span class="fa fa-plus"></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(() => {
            var closebtns = document.getElementsByClassName("glyphicon glyphicon-remove");
            var i;

            /* Loop through the elements, and hide the parent, when clicked on */
            for (i = 0; i < closebtns.length; i++) {
                closebtns[i].addEventListener("click", function () {
                    $(this).parent().parent().remove();
                });
            }

            $('#addiadiem').click(() => {
                var z = $("#dropdowndiadiem > option:selected").val();
                if (z > 0) {
                    var zz = $("#dropdowndiadiem > option:selected").text();
                    $('.list-group').append('<li class="list-group-item"><input type="text" name="listPlaces" value="' + z + '" hidden /><span class="name">' + zz + '</span><label class="btn btn-default btn-xs pull-right remove-item"> <span class="glyphicon glyphicon-remove"></span></label></li>');
                }
                closebtns = document.getElementsByClassName("glyphicon glyphicon-remove");
                for (i = 0; i < closebtns.length; i++) {
                    closebtns[i].addEventListener("click", function () {
                        $(this).parent().parent().remove();
                    });
                }
                $("#dropdowndiadiem").val(0);

            });
        });
    </script>
}

projecttour/Views/tours/Delete.cshtml
@model projecttour.Models.tour

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tour_ten)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tour_mota)
        </dd>

        <dt>
            Block
        </dt>

        <dd>
            @Html.DisplayFor(model => model.block)
        </dd>

        <dt>
            Type
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tour_loai.loai_ten)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

projecttour/Views/tours/Details.cshtml
@model projecttour.Models.tour

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["idplace"])

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>tour</h4>
            <dl class="dl-horizontal">
                <dt>
                   Tên tour
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tour_ten)
                </dd>

                <dt>
                  Mô tả
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tour_mota)
                </dd>

                <dt>
                   Trạng thái
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.block)
                </dd>

                <dt>
                   Loại tour
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tour_loai.loai_ten)
                </dd>

            </dl>
        </div>
        <div class="col-md-6">
            <h4>Địa điểm</h4>


            @* <label class="control-label col-md-3" for="loai_id">Địa điểm</label>*@
        
            <ul>
                @foreach (var item in ViewBag.cityoftour)
                {
                    <li style=""><span>@item.Value</span> - <span> @item.Text</span></li>
                   
                }
            </ul>
           @* <p>----</p>
            @using (Html.BeginForm("Details", "tours", FormMethod.Post))
            {
                <input hidden type="text" value="" id="currentidtour" name="listPlaces"/>
                <ul id="listdiadiem">
                </ul>

                <select class="form-control" id="dropdowndiadiem" name="diadiem">
                    <option value="0" selected>Select a place</option>
                    @foreach (var item in ViewBag.diadiem)
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                </select>
                <input id="addiadiem" type="button" value="Add" />
                <input id="submitaddplace" type="submit" value="Update" />
            }*@

        </div>

        
       


    </div>

</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.tour_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/Scripts/custom.js")
}

projecttour/Views/tours/Edit.cshtml
@model projecttour.Models.tour

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tour</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.tour_id)

        <div class="form-group">
            @Html.LabelFor(model => model.tour_ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tour_ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tour_ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tour_mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tour_mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tour_mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.loai_id, "loai_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("loai_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.loai_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.block, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.block, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.block, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

projecttour/Views/tours/Index.cshtml
@model IEnumerable<projecttour.Models.tour>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card w-100">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6 text-danger text-uppercase">
                <strong>Danh sách Tour</strong>
            </div>

            <div class="col-md-6 text-right">
                <a href="@Url.Action("Create")" class="btn btn-sm btn-success" data-toggle="tooltip" title="Thêm mới">
                    <span class="fa fa-plus-square"></span>
                </a>
            </div>
        </div>
    </div>
    <div class="card-block p-3">
        <table class="table table-bordered table-hover table-striped w-100">
                <tr>
                    <th>
                        #
                        @*@Html.DisplayNameFor(model => model.tour_ten)*@
                    </th>
                    <th>
                        Tên tour
                        @*@Html.DisplayNameFor(model => model.tour_ten)*@
                    </th>
                    <th>
                        Mô tả
                        @* @Html.DisplayNameFor(model => model.tour_mota)*@
                    </th>
                    <th>
                        Trạng thái
                        @*@Html.DisplayNameFor(model => model.block)*@
                    </th>
                    <th>
                        Loại tour
                        @*@Html.DisplayNameFor(model => model.tour_loai.loai_ten)*@
                    </th>
                    <th>
                        Giá
                    </th>
                    <th>Địa điểm</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.tour_id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tour_ten)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tour_mota)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.block)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tour_loai.loai_ten)
                        </td>
                        <td>
                            <a href="/tour_gia?tour=@item.tour_id" class="btn btn-sm btn-success" data-toggle="tooltip" title="Xem">
                                <span class="fa fa-book-open"></span>
                            </a>
                        </td>
                        <td>
                            @* @Html.ActionLink("Edit", "Edit", new { id = item.tour_id }) |*@
                            <a href="@Url.Action("Details",new { id = item.tour_id })" class="btn btn-sm btn-success" data-toggle="tooltip" title="Xem">
                                <span class="fa fa-book-open"></span>
                            </a>
                            @*    @Html.ActionLink("Delete", "Delete", new { id = item.tour_id })*@
                        </td>
                    </tr>
                }

            </table>
        </div>
</div>