projecttour/Models/tour_doan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tour_doan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tour_doan()
        {
            this.tour_nguoidi = new HashSet<tour_nguoidi>();
            this.tour_chiphi = new HashSet<tour_chiphi>();
        }
    
        public int doan_id { get; set; }
        public int tour_id { get; set; }
        public string doan_name { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> doan_ngaydi { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> doan_ngayve { get; set; }
        public string doan_chitietchuongtrinh { get; set; }
        public Nullable<int> id_gia_tour { get; set; }
    
        public virtual tour tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_nguoidi> tour_nguoidi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_chiphi> tour_chiphi { get; set; }
    }
}

projecttour/Controllers/tour_doanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projecttour.Models;

namespace projecttour.Controllers
{
    public class tour_doanController : Controller
    {
        private tour_dulichEntities1 db = new tour_dulichEntities1();
        // load địa điểm & chi phí
       
        // GET: tour_doan
        public ActionResult Index()
        {
            var tour_doan = db.tour_doan.Include(t => t.tour);
            List<string> tam = new List<string>();

            tour_doan.ToList().ForEach(e =>
            {
                int zz = (int)e.id_gia_tour;
                string z = (from vnd in db.tour_gia
                            where vnd.gia_id == zz
                            select vnd.gia_sotien).First().ToString();
                tam.Add(z);
            });
            ViewBag.CostList = tam;
            return View(tour_doan.ToList());
        }
        public ActionResult Chiphi(int? id)
        {
            // tour
            int tourid = db.tour_doan
                                .Where(c => c.doan_id == id)
                                .Select(c => c.tour_id).First();
            ViewBag.tour_id = db.tours
                                .Where(c => c.tour_id == tourid)
                                .Select(c => new SelectListItem { Value = c.tour_id.ToString(), Text = c.tour_ten})
                                .First();
            // doan
            ViewBag.doanname = db.tour_doan
                                .Where(c => c.doan_id == id)
                                .Select(c => c.doan_name).First();
            ViewBag.doanid = id;

            //ls chi phi
            ViewBag.Listchiphi = db.tour_loaichiphii
                                .Where(c => c.cp_id!=0)
                                .Select(c => new SelectListItem { Value = c.cp_id.ToString(), Text = c.cp_ten })
                                .ToList();
            var tour_Chiphis = db.tour_chiphi
                                .Where(c => c.doan_id == id)
                                .ToList();
            ViewBag.listchiphii = tour_Chiphis;
            List<string> tam = new List<string>();
            int result = 0;
            tour_Chiphis.ForEach(e =>
            {
                if (tour_Chiphis.Count > 0)
                {
                    int tt = int.Parse(e.chiphi_total.ToString());
                    result += tt;
                    int zz = (int)e.loaichiphi;
                    string z = (from vnd in db.tour_loaichiphii
                                where vnd.cp_id == zz
                                select vnd.cp_ten).First().ToString();
                    tam.Add(z);
                }
            });
            ViewBag.namechiphi = tam;
            ViewBag.total = result;


            return View();
        }
        [HttpPost]
        public ActionResult Chiphi()
        {
            int idTour = int.Parse(Request["tour_id"]);
            int idDoan =int.Parse(Request["doan_name"]);
            int loaichiphi=int.Parse(Request["lcp"]); ;
            string hoadon= Request["hoa_don"];
            string noidung = Request["noi_dung"];
            DateTime ngaylhd = DateTime.Now;
            int sotien = int.Parse(Request["sotien"]);

            tour_chiphi z = new tour_chiphi();
            int generateId = 0;
            if(db.tour_chiphi.ToList().Count>0) generateId = (from id in db.tour_chiphi select id).Max(e => e.chiphi_id);
            z.chiphi_id = generateId + 1;
            z.doan_id = idDoan;
            z.chiphi_total = sotien;
            z.loaichiphi = loaichiphi;
            z.hoadon = hoadon;
            z.noidung = noidung;
            z.chiphi_chitiet = "0,";
            z.ngaylap = ngaylhd;
            db.tour_chiphi.Add(z as tour_chiphi);
            db.SaveChanges();

            return Redirect("/tour_doan/Chiphi/" + idDoan);
        }
        // GET: tour_doan/Details/5
        public ActionResult Details(int? id)
        {
            //load data customers
            ViewBag.customers = db.tour_khachhang
                                .Select(c => new SelectListItem { Value = c.kh_id.ToString(), Text = c.kh_ten + "-" + c.kh_cmnd })
                                .ToList();
            //load data staffs
            ViewBag.staffs = db.tour_nhanvien
                                .Select(c => new SelectListItem { Value = c.nv_id.ToString(), Text = c.nv_ten + "-" + c.nv_nhiemvu })
                                .ToList();
           
           
            //start load staffs current
           

            ViewBag.idtourcurrent = id;
            //end
            //start load customers current
            
            List<SelectListItem> listcustomerCurrent = new List<SelectListItem>();
            if(db.tour_nguoidi.Where(e => e.doan_id == id && e.nguoidi_dsnhanvien == "0").ToList().Count>0)
            db.tour_nguoidi.Where(e => e.doan_id == id && e.nguoidi_dsnhanvien=="0").ToList().ForEach(ee =>
            {
                listcustomerCurrent.Add(new SelectListItem { Value = ee.nguoidi_dskhachhang, Text = db.tour_khachhang.Where(eee => eee.kh_id.ToString() == ee.nguoidi_dskhachhang).Select(eee => eee.kh_ten).First() + "-" + db.tour_khachhang.Where(eee => eee.kh_id.ToString() == ee.nguoidi_dskhachhang).Select(eee => eee.kh_cmnd).First() });
            });
            
            ViewBag.listcustomerCurrent = listcustomerCurrent;

            List<SelectListItem> liststaffCurrent = new List<SelectListItem>();
            if (db.tour_nguoidi.Where(e => e.doan_id == id && e.nguoidi_dsnhanvien == "0").ToList().Count > 0)
                db.tour_nguoidi.Where(e => e.doan_id == id && e.nguoidi_dskhachhang == "0").ToList().ForEach(ee =>
            {
                liststaffCurrent.Add(new SelectListItem { Value = ee.nguoidi_dsnhanvien, Text = db.tour_nhanvien.Where(eee => eee.nv_id.ToString() == ee.nguoidi_dsnhanvien).Select(eee => eee.nv_ten).First() + "-" + db.tour_nhanvien.Where(eee => eee.nv_id.ToString() == ee.nguoidi_dsnhanvien).Select(eee => eee.nv_nhiemvu).First() });
            });

            ViewBag.listcustomerCurrent = listcustomerCurrent;
            ViewBag.listStaffCurrent = liststaffCurrent;
            //end
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour_doan tour_doan = db.tour_doan.Find(id);
            if (tour_doan == null)
            {
                return HttpNotFound();
            }
            return View(tour_doan);
        }
        [HttpPost]
        public ActionResult Detail( ICollection<string> listCustommer, ICollection<string> listStaffs)
        {
            string[] array = new string[listCustommer.Count];
            listCustommer.CopyTo(array, 0);

            string[] array1 = new string[listStaffs.Count];
            listStaffs.CopyTo(array1, 0);
            TempData["idplace"] = "<script>alert('" + array[0] + "');</script>";

            int idcurrentdoan = int.Parse(Request["idcurrent"]);
            // delete all khach hang vs nhan vien
            db.tour_nguoidi.Where(e => e.doan_id == idcurrentdoan).ToList().ForEach(ee =>
             {
                 db.tour_nguoidi.Remove(db.tour_nguoidi.Where(eee => eee.nguoidi_id == ee.nguoidi_id).FirstOrDefault());
                 db.SaveChanges();
             });
            //
            
            for (int i = 1; i < array.Length; i++)
            {
                int generateId = 0;
                if (db.tour_nguoidi.ToList().Count > 0)
                {
                    generateId = (from id in db.tour_nguoidi select id).Max(e => e.nguoidi_id);
                }
                tour_nguoidi ndtam = new tour_nguoidi();
                ndtam.nguoidi_id = generateId + 1;
                ndtam.doan_id = idcurrentdoan;
                ndtam.nguoidi_dsnhanvien = "0";
                ndtam.nguoidi_dskhachhang = array[i];
                db.tour_nguoidi.Add(ndtam);
                db.SaveChanges();
            }
            for (int i = 1; i < array1.Length; i++)
            {
                int generateId = 0;
                if (db.tour_nguoidi.ToList().Count > 0)
                {
                    generateId = (from id in db.tour_nguoidi select id).Max(e => e.nguoidi_id);
                }
                tour_nguoidi ndtam = new tour_nguoidi();
                ndtam.nguoidi_id = generateId + 1;
                ndtam.doan_id = idcurrentdoan;
                ndtam.nguoidi_dsnhanvien = array1[i];
                ndtam.nguoidi_dskhachhang = "0";
                db.tour_nguoidi.Add(ndtam);
                db.SaveChanges();
            }
            return Redirect("https://localhost:44341/tour_doan/Details/" + idcurrentdoan);
        }
        // GET: tour_doan/Create
        public ActionResult Create()
        {
            ViewBag.CostList = from c in db.tour_gia select c;
            ViewBag.tour_id = new SelectList(db.tours, "tour_id", "tour_ten");
            return View();
        }

        // POST: tour_doan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "doan_id,tour_id,doan_name,doan_ngaydi,doan_ngayve,doan_chitietchuongtrinh")] tour_doan tour_doan)
        {
            //Request["cost"] idtour
            int stsb = int.Parse(Request["costvalue"]);
            int zzz = db.tour_gia.Where(a => a.gia_sotien == stsb && a.tour_id== tour_doan.tour_id)
                     .Select(a => a.gia_id)
                     .First();
            if (ModelState.IsValid)
            {
                int generateIdTour_doan = 0;

projecttour/Views/tour_doan/Chiphi.cshtml
@{
    ViewBag.Title = "Chiphi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card w-100">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 text-danger text-uppercase">
                    <strong>Chi phí</strong>
                </div>
                <div class="col-md-6 text-right">
                    <a href="@Url.Action("Index")" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Thoát">
                        <span class="fa fa-reply"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-block p-3">
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label>Tên tour</label>
                        <select class="form-control" id="tour_id" name="tour_id" disabled>
                            <option value="@ViewBag.tour_id.Value">@ViewBag.tour_id.Text</option>

                        </select>
                        <span class="field-validation-valid text-danger" data-valmsg-for="tour_id" data-valmsg-replace="true"></span>
                        <input type="text" value="@ViewBag.tour_id.Value" name="tour_id" hidden />
                    </div>
                    <div class="form-group">
                        <label>Tên đoàn</label>
                        <select class="form-control" id="tour_id" name="doan_name" disabled>

                            <option value="@ViewBag.doanid">@ViewBag.doanname</option>

                        </select>
                        <span class="field-validation-valid text-danger" data-valmsg-for="tour_id" data-valmsg-replace="true"></span>
                        <input type="text" value="@ViewBag.doanid" name="doan_name" hidden />
                    </div>
                    <div class="form-group">
                        <label>Loại chi phí</label>
                        <select class="form-control" id="tour_id" name="lcp">

                            @{
                                foreach (var e in ViewBag.Listchiphi)
                                {
                                    <option value="@e.Value">@e.Text</option>
                                }
                            }

                        </select>
                        <span class="field-validation-valid text-danger" data-valmsg-for="tour_id" data-valmsg-replace="true"></span>
                    </div>
                    <div class="form-group">
                        <label>Hóa đơn</label>
                        <input class="form-control text-box single-line" id="doan_name" name="hoa_don" type="text" value="" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="doan_name" data-valmsg-replace="true"></span>
                    </div>
                    <div class="form-group">
                        <label>Nội dung</label>
                        <input class="form-control text-box single-line" id="doan_name" name="noi_dung" type="text" value="" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="doan_name" data-valmsg-replace="true"></span>
                    </div>
                    <div class="form-group">
                        <label>Ngày hóa đơn</label>
                        <input class="form-control text-box single-line" data-val="true" data-val-date="The field doan_ngaydi must be a date." id="doan_ngaydi" name="ngaylhd" type="date" value="" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="doan_ngaydi" data-valmsg-replace="true"></span>
                    </div>
                    <div class="form-group">
                        <label>Số tiền</label>
                        <input class="form-control text-box single-line" id="doan_name" name="sotien" type="text" value="" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="doan_name" data-valmsg-replace="true"></span>
                    </div>
                    <button class="btn btn-sm btn-success">Save</button>
                </div>
                <div class="col-md-7">
                    <table class="table table-bordered table-hover table-striped w-100">
                        <tr>
                            <th>STT</th>
                            <th>Hoa don</th>
                            <th>Loai chi phi</th>
                            <th>Ten chi phi</th>
                            <th>So tien</th>
                        </tr>

                        @{
                            int i = 1;
                            foreach (var e in ViewBag.listchiphii)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@e.hoadon</td>
                                    <td>@ViewBag.namechiphi[i - 1]</td>
                                    <td>@e.noidung</td>
                                    <td>@e.chiphi_total</td>


                                </tr>
                                i = i + 1;

                            }
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>


}

projecttour/Views/tour_doan/Create.cshtml
@model projecttour.Models.tour_doan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card w-100">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 text-danger text-uppercase">
                    <strong>Thêm đoàn</strong>
                </div>

                <div class="col-md-6 text-right">
                    <button id="createDoan" type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" title="Thêm">
                        <span class="fa fa-plus-square"></span>
                    </button>
                    <a href="@Url.Action("Index")" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Thoát">
                        <span class="fa fa-reply"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-block p-3">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tour</label>
                        @Html.DropDownList("tour_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.tour_id, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Tên Đoàn</label>
                        @Html.EditorFor(model => model.doan_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.doan_name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Chi tiết</label>
                        @Html.EditorFor(model => model.doan_chitietchuongtrinh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.doan_chitietchuongtrinh, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Ngày đi</label>
                        @Html.EditorFor(model => model.doan_ngaydi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.doan_ngaydi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Ngày về</label>
                        @Html.EditorFor(model => model.doan_ngayve, new { htmlAttributes = new { @class = "datepicker form-control" } })
                        @Html.ValidationMessageFor(model => model.doan_ngayve, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Giá</label>
                        <select class="form-control" id="costlist" name="cost">

                            @{
                                foreach (var e in ViewBag.CostList)
                                {
                                    <option value="@e.tour_id">@e.gia_sotien </option>
                                }
                            }

                        </select>
                        <input type="text" value="" id="costvalue" name="costvalue" hidden />
                        <span class="field-validation-valid text-danger" data-valmsg-for="" data-valmsg-replace="true"></span>
                        
                    </div>
                   
                </div>
            </div>
        </div>
    </div>


}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function () {
            $("#createDoan").click(() => {
                $("#costvalue").val($("#costlist > option:selected").text());
            })
            //alert($("option:selected").val());
            var f = $("option:selected").val();
            $('#costlist > option').each(function () {
                if ($(this).val() == f) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
                $('#costlist').val(f);
            })
            var filter = $("option:selected").val();
            $("#tour_id").change(() => {

                //alert($("option:selected").val());
                var filter = $("option:selected").val();
                $('#costlist > option').each(function () {
                    if ($(this).val() == filter) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }
                    $('#costlist').val(filter);
                })
            });

        });

    </script>
}

projecttour/Views/tour_doan/Delete.cshtml
@model projecttour.Models.tour_doan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card w-100">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 text-danger text-uppercase">
                    <strong>Are you sure you want to delete this?</strong>
                </div>
                <div class="col-md-6 text-right">
                    <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Xóa">
                        <span class="fa fa-trash"></span>
                    </button>
                    <a href="@Url.Action("Index")" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Thoát">
                        <span class="fa fa-reply"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>

}

projecttour/Views/tour_doan/Details.cshtml
@model projecttour.Models.tour_doan

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Detail", "tour_doan", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="card w-100">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 text-danger text-uppercase">
                    <strong>Thêm người đi</strong>
                </div>
                <input type="text" value="@ViewBag.idtourcurrent" name="idcurrent" hidden />
                <div class="col-md-6 text-right">

                    <a href="@Url.Action("Index")" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Thoát">
                        <span class="fa fa-reply"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-block p-3">
            <div class="row">
                <div class="col-md-2">
                    <h4>Chi tiết đoàn</h4>
                    <dl class="dl-horizontal">
                        <dt>
                            Tên đoàn
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.doan_name)
                        </dd>


                        <dt>
                            Tên tour
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.tour.tour_ten)
                        </dd>

                    </dl>
                </div>
                <div class="col-md-5">
                    <ul id="listcustomers">
                        <input type="text" name="listCustommer" value="0" hidden />
                        @foreach (var e in ViewBag.listcustomerCurrent)
                        {
                            @*<p>@e.Value</p>
                        <p>@e.Text</p>*@
                            <li class="list-group-item">
                                <input type="text" name="listCustommer" value="@e.Value" hidden />
                                <span class="name">@e.Text</span>
                                <label class="btn btn-default btn-xs pull-right remove-item">
                                    <span class="glyphicon glyphicon-remove"><span class="fa fa-trash"></span></span>
                                </label>
                            </li>
                        }

                    </ul>
                    <select class="form-control" id="dropdowncustomers" name="diadiem">
                        <option value="0" selected>Select a customer</option>
                        @foreach (var item in ViewBag.customers)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                    <input type="button" value="Add customer" class="btn btn-sm btn-success mt-3" id="addcustomer" />



                </div>
                <div class="col-md-5">
                    <input type="text" name="listStaffs" value="0" hidden />
                    <ul id="liststaffs">

                        @foreach (var e in ViewBag.listStaffCurrent)
                        {
                            @*<p>@e.Value</p>
                <p>@e.Text</p>*@

                            <li class="list-group-item">
                                <input type="text" name="listStaffs" value="@e.Value" hidden />
                                <span class="name">@e.Text</span>
                                <label class="btn btn-default btn-xs pull-right remove-item">
                                    <span class="glyphicon glyphicon-remove"><span class="fa fa-trash"></span></span>
                                </label>
                            </li>
                        }

                    </ul>
                    <select class="form-control" id="dropdownstaffs" name="diadiem">
                        <option value="0" selected>Select a staff</option>
                        @foreach (var item in ViewBag.staffs)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                    <input type="button" value="Add staff" class="btn btn-sm btn-success mt-3" id="addstaff" />



                </div>
            </div>
            <div class="text-center">
                <input type="submit" class="btn btn-sm btn-success" value="Update" id="submitdoan" />
            </div>
            
        </div>
    </div>


}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.doan_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@section Scripts {
    @Scripts.Render("~/Scripts/custom.js")
    <script>
        $(document).ready(() => {
            var closebtns = document.getElementsByClassName("glyphicon glyphicon-remove");
            var i;

            /* Loop through the elements, and hide the parent, when clicked on */
            for (i = 0; i < closebtns.length; i++) {
                closebtns[i].addEventListener("click", function () {
                    $(this).parent().parent().remove();
                });
            }

            $('#addcustomer').click(() => {
                var z = $("#dropdowncustomers > option:selected").val();
                if (z > 0) {
                    var zz = $("#dropdowncustomers > option:selected").text();
                    $('#listcustomers').append('<li class="list-group-item"><input type="text" name="listCustommer" value="' + z + '" hidden /><span class="name">' + zz + '</span><label class="btn btn-default btn-xs pull-right remove-item"> <span class="glyphicon glyphicon-remove"><span class="fa fa-trash"></span></span></label></li>');
                }
                closebtns = document.getElementsByClassName("glyphicon glyphicon-remove");
                for (i = 0; i < closebtns.length; i++) {
                    closebtns[i].addEventListener("click", function () {
                        $(this).parent().parent().remove();
                    });
                }
                $("#dropdowncustomers").val(0);

            });

            $('#addstaff').click(() => {
                var t = $("#dropdownstaffs > option:selected").val();
                if (t > 0) {
                    var tt = $("#dropdownstaffs > option:selected").text();
                    $('#liststaffs').append('<li class="list-group-item"><input type="text" name="listStaffs" value="' + t + '" hidden /><span class="name">' + tt + '</span><label class="btn btn-default btn-xs pull-right remove-item"> <span class="glyphicon glyphicon-remove"><span class="fa fa-trash"></span></span></label></li>');
                }
                closebtns = document.getElementsByClassName("glyphicon glyphicon-remove");
                for (i = 0; i < closebtns.length; i++) {
                    closebtns[i].addEventListener("click", function () {
                        $(this).parent().parent().remove();
                    });
                }
                $("#dropdownstaffs").val(0);

            });


        });
    </script>
}