projecttour/Models/tour_gia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_gia
    {
        public int gia_id { get; set; }
        public Nullable<decimal> gia_sotien { get; set; }
        public Nullable<System.DateTime> gia_tungay { get; set; }
        public Nullable<System.DateTime> gia_denngay { get; set; }
        public Nullable<int> tour_id { get; set; }
    }
}

projecttour/Controllers/tour_giaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projecttour.Models;

namespace projecttour.Controllers
{
    public class tour_giaController : Controller
    {
        private tour_dulichEntities1 db = new tour_dulichEntities1();

        // GET: tour_gia
        public ActionResult Index(string tour)
        {
            ViewBag.tours = from t in db.tours select t;
            ViewBag.Costs = "";
            ViewBag.choose = 0;
            if (!String.IsNullOrEmpty(tour))
            {
                int id = Int32.Parse(tour);
                ViewBag.choose = id;
                ViewBag.Costs = from c in db.tour_gia
                                where c.tour_id == id
                                select c;
            }
            return View();
        }
        [HttpPost]
        public ActionResult Find()
        {
            string id = HttpContext.Request.Form["selectedValue"];
            if (id == "0") return RedirectToAction("index");
            return RedirectToAction("index", new {tour = id });
        }

        public ActionResult Create()
        {
            ViewBag.tours = from t in db.tours select t;
            return View();
        }














        // GET: tour_gia/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour_gia tour_gia = db.tour_gia.Find(id);
            if (tour_gia == null)
            {
                return HttpNotFound();
            }
            return View(tour_gia);
        }

        

        // POST: tour_gia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "gia_sotien,gia_tungay,gia_denngay,tour_id")] tour_gia tour_gia)
        {
            int generateID = 0;
            if(db.tour_gia.ToList().Count>0) generateID = (from id in db.tour_gia select id).Max(e => e.gia_id);
            tour_gia.gia_id = generateID + 1;
            if (ModelState.IsValid)
            {
                db.tour_gia.Add(tour_gia);
                db.SaveChanges();
                return RedirectToAction("index", new { tour = tour_gia.tour_id });
            }

            return RedirectToAction("index", new { tour = tour_gia.tour_id });
        }

        // GET: tour_gia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour_gia tour_gia = db.tour_gia.Find(id);
            if (tour_gia == null)
            {
                return HttpNotFound();
            }
            ViewBag.tour = db.tour_gia.Find(id);
            /*ViewBag.tour.gia_tungay =  ViewBag.tour.gia_tungay.ToString("dd/MM/yyyy");
            ViewBag.tour.gia_denngay = ViewBag.tour.gia_denngay.ToString("dd/MM/yyyy");*/
            ViewBag.tours = from t in db.tours select t;
            return View();
        }

        // POST: tour_gia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include = "gia_id,gia_sotien,gia_tungay,gia_denngay,tour_id")] tour_gia tour_gia)
        {
           
            if (ModelState.IsValid)
            {
                db.Entry(tour_gia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("index", new { tour = tour_gia.tour_id });
            }
            return RedirectToAction("index", new { tour = tour_gia.tour_id });
        }

        // GET: tour_gia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour_gia tour_gia = db.tour_gia.Find(id);
            if (tour_gia == null)
            {
                return HttpNotFound();
            }
            return View(tour_gia);
        }

        // POST: tour_gia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tour_gia tour_gia = db.tour_gia.Find(id);
            db.tour_gia.Remove(tour_gia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projecttour/Views/tour_gia/Create.cshtml
@model projecttour.Models.tour_gia

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card w-100">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 text-danger text-uppercase">
                    <strong>Thêm giá tour</strong>
                </div>

                <div class="col-md-6 text-right">
                    <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" title="Thêm">
                        <span class="fa fa-plus-square"></span>
                    </button>
                    <a href="@Url.Action("Index")" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Thoát">
                        <span class="fa fa-reply"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-block p-3">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tên Tour</label>
                        <select class="form-control" id="block" name="tour_id">
                            @{
                                foreach (var item in ViewBag.tours)
                                {
                                    <option value="@item.tour_id">@item.tour_ten</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Số tiền</label>
                        <input class="form-control text-box single-line" data-val="true" data-val-number="The field gia_sotien must be a number." id="gia_sotien" name="gia_sotien" type="text" value="" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="gia_sotien" data-valmsg-replace="true"></span>
                    </div>
                    
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Từ ngày</label>
                        <input class="form-control text-box single-line" data-val="true" data-val-date="The field gia_tungay must be a date." id="gia_tungay" name="gia_tungay" type="date" value="" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="gia_tungay" data-valmsg-replace="true"></span>
                    </div>
                    <div class="form-group">
                        <label>Đến ngày</label>
                        <input class="form-control text-box single-line" data-val="true" data-val-date="The field gia_denngay must be a date." id="gia_denngay" name="gia_denngay" type="date" value="" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="gia_denngay" data-valmsg-replace="true"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>


}
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

projecttour/Views/tour_gia/Delete.cshtml
@model projecttour.Models.tour_gia

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tour_gia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.gia_sotien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia_sotien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gia_tungay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia_tungay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gia_denngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia_denngay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tour_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tour_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

projecttour/Views/tour_gia/Details.cshtml
@model projecttour.Models.tour_gia

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tour_gia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.gia_sotien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia_sotien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gia_tungay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia_tungay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gia_denngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia_denngay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tour_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tour_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.gia_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

projecttour/Views/tour_gia/Edit.cshtml
@model projecttour.Models.tour_gia

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<div class="form-horizontal">
    <h4>tour_gia</h4>
    <hr />

    @using (Html.BeginForm("Edit", "tour_gia", FormMethod.Post))
    {
        <input type="text" value="@ViewBag.tour.gia_id" name="gia_id" hidden />
        
        <div class="form-group">
            <label class="control-label col-md-2" for="gia_sotien">gia_sotien</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-number="The field gia_sotien must be a number." id="gia_sotien" name="gia_sotien" type="text" value="@ViewBag.tour.gia_sotien" />
                <span class="field-validation-valid text-danger" data-valmsg-for="gia_sotien" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="gia_tungay">gia_tungay</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-date="The field gia_tungay must be a date." id="gia_tungay" name="gia_tungay" type="date" value="@ViewBag.tour.gia_tungay.ToString("yyyy-MM-dd")" />
                <span class="field-validation-valid text-danger" data-valmsg-for="gia_tungay" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="gia_denngay">gia_denngay</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-date="The field gia_denngay must be a date." id="gia_denngay" name="gia_denngay" type="date" value="@ViewBag.tour.gia_denngay.ToString("yyyy-MM-dd")" />
                <span class="field-validation-valid text-danger" data-valmsg-for="gia_denngay" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="block">Tour</label>
            <div class="col-md-10">

                <select class="form-control" id="block" name="tour_id" disabled>
                    @{
                        foreach (var item in ViewBag.tours)
                        {
                            if (item.tour_id == ViewBag.tour.tour_id)
                            {
                                <option value="@item.tour_id">@item.tour_ten</option>
                                <input type="text" value="@item.tour_id" name="tour_id" hidden />
                            }
                        }
                    }
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="block" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>

    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

projecttour/Views/tour_gia/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card w-100">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6 text-danger text-uppercase">
                <strong>Danh sách Giá Tour</strong>
            </div>

            <div class="col-md-6 text-right">
                <a href="/tour_gia/Create" class="btn btn-sm btn-success" data-toggle="tooltip" title="Thêm mới">
                    <span class="fa fa-plus-square"></span>
                </a>
            </div>
        </div>
    </div>
    <div class="card-block p-3">
        @using (Html.BeginForm("Find", "tour_gia", FormMethod.Post))
        {
            <div class="form-inline">
                @* <p>@ViewBag.choose</p>*@
                <label class="mr-3">Chọn tour: </label>
                <select class="form-control mr-3" name="selectedValue">
                    @{
                        if (ViewBag.choose == 0)
                        {
                            <option selected value="0">Select tour</option>

                        }
                        else
                        {
                            <option value="0">Select tour</option>
                        }
                        foreach (var item in ViewBag.tours)
                        {
                            if (ViewBag.choose == item.tour_id)
                            {
                                <option selected value="@item.tour_id">@item.tour_ten</option>
                            }
                            else
                            {
                                <option value="@item.tour_id">@item.tour_ten</option>
                            }
                        }
                    }
                </select>
                <button class="btn btn-sm btn-success mr-3">Xem</button>
            </div>
        }
    <table class="table table-bordered table-hover table-striped w-100 mt-3">
        <tr>
            <th>
                STT
                @*@Html.DisplayNameFor(model => model.tour_ten)*@
            </th>
            <th>
                Cost
                @*@Html.DisplayNameFor(model => model.tour_ten)*@
            </th>
            <th>
                From
                @* @Html.DisplayNameFor(model => model.tour_mota)*@
            </th>
            <th>
                To
                @*@Html.DisplayNameFor(model => model.block)*@
            </th>
            <th>
                Chức năng
            </th>
        </tr>
        @{ int i = 1;}
        @foreach (var item in ViewBag.Costs)
        {
            <tr>
                <td>@i</td>
                <td>
                    @item.gia_sotien
                </td>
                <td>
                    @item.gia_tungay.ToString(string.Format("dd/MM/yyyy"))
                </td>
                <td>
                   @item.gia_denngay.ToString(string.Format("dd/MM/yyyy"))
                </td>
                <td>
                    <a href="/tour_gia/Edit/@item.gia_id" class="btn btn-sm btn-success" data-toggle="tooltip" title="Sửa"><span class="fa fa-cog"></span></a>
                </td>
                @{ i++;}
            </tr>
        }

    </table>
    </div>
</div>