projecttour/Models/tour_nguoidi.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_nguoidi
    {
        public int nguoidi_id { get; set; }
        public int doan_id { get; set; }
        public string nguoidi_dsnhanvien { get; set; }
        public string nguoidi_dskhachhang { get; set; }
    
        public virtual tour_doan tour_doan { get; set; }
    }
}

projecttour/Controllers/tour_nguoidiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projecttour.Models;

namespace projecttour.Controllers
{
    public class tour_nguoidiController : Controller
    {
        private tour_dulichEntities1 db = new tour_dulichEntities1();

        // GET: tour_nguoidi
        public class thongke
        {
            public int idtour { get; set; }
            public string tour { get; set; }
            public int tongdoandi { get; set; }
            public int tongdanhthu { get; set; }
            public int tongchiphi { get; set; }
            public int lai { get; set; }
            public int sokhach { get; set; }
            public int giatour { get; set; }
        }
        public ActionResult Index()
        {
            var tour_nguoidi = db.tour_nguoidi.Include(t => t.tour_doan);
            List<thongke> listtk = new List<thongke>();
            List<int> ttt = new List<int>();
            var tourlist = db.tours.ToList();
            tourlist.ForEach(e =>
            {
                thongke tk = new thongke();
                tk.idtour = e.tour_id;
                tk.tour = e.tour_ten;
                
                tk.tongdoandi = db.tour_doan.Count(element => element.tour_id==e.tour_id );

                int tdt = 0;
                int tcp = 0;
                // tong chi phi = doan gia * so nguoi di
                db.tour_doan.Where(ee => ee.tour_id == e.tour_id).ToList().ForEach(z =>
                 {
                     // tong nguoi di * gia -> doanh thu
                     string giadoan = db.tour_gia.First(zz => zz.gia_id == z.id_gia_tour).gia_sotien.ToString();
                     int nguoidi = db.tour_nguoidi.Where(zz => zz.doan_id == z.doan_id && zz.nguoidi_dsnhanvien=="0").Count();
                     
                     tdt += nguoidi * int.Parse(giadoan);

                     //all chi phi total
                     db.tour_chiphi.Where(zz => zz.doan_id == z.doan_id).ToList().ForEach(zzz =>
                     {
                         string ztamz = db.tour_chiphi.First(zzzz => zzzz.chiphi_id == zzz.chiphi_id).chiphi_total.ToString();
                         tcp += int.Parse(ztamz);
                     });
                     
                 });
                tk.tongchiphi = tcp;
                tk.tongdanhthu = tdt;
                
                listtk.Add(tk);
                //
            });
            ViewBag.listCost = listtk.ToList();
            return View(listtk.ToList());
        }


        // GET: tour_nguoidi/Edit/5
        public ActionResult Chitiet(int? id)
        {
            /*if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
            tour_nguoidi tour_nguoidi = db.tour_nguoidi.Find(id);
           /* if (tour_nguoidi == null)
            {
                return HttpNotFound();
            }*/
            List<thongke> listtk = new List<thongke>();
            
            ViewBag.listTour = db.tours.ToList();
            db.tour_doan.Where(ee => ee.tour_id == id).ToList().ForEach(z =>
            {
                // tong nguoi di * gia -> doanh thu
                thongke tKe = new thongke();
                tKe.idtour = z.doan_id;
                tKe.tour = z.doan_name;
                string giadoan = db.tour_gia.First(zz => zz.gia_id == z.id_gia_tour).gia_sotien.ToString();
                int nguoidi = db.tour_nguoidi.Where(zz => zz.doan_id == z.doan_id).Count();
                tKe.sokhach = nguoidi;
                tKe.giatour = int.Parse(giadoan);
                tKe.tongdanhthu = nguoidi * int.Parse(giadoan);
                //all chi phi total
                int tcp = 0;
                db.tour_chiphi.Where(zz => zz.doan_id == z.doan_id).ToList().ForEach(zzz =>
                {
                    string ztamz = db.tour_chiphi.First(zzzz => zzzz.chiphi_id == zzz.chiphi_id).chiphi_total.ToString();
                    tcp += int.Parse(ztamz);
                });
                tKe.tongchiphi = tcp;
                listtk.Add(tKe);
            });
            return View(listtk.ToList());
        }
        [HttpPost]
        public ActionResult Chitiet()
        {
            string id = HttpContext.Request.Form["selectedValue"];
            return Redirect("https://localhost:44341/tour_nguoidi/Chitiet/" + id);
        }

    }
}

projecttour/Views/tour_nguoidi/Chitiet.cshtml
@model IEnumerable<projecttour.Controllers.tour_nguoidiController.thongke>

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card w-100">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6 text-danger text-uppercase">
                <strong>Danh sách Giá Tour</strong>
            </div>
            <div class="col-md-6 text-right">
                <a href="@Url.Action("Index")" class="btn btn-sm btn-danger" data-toggle="tooltip" title="Thoát">
                    <span class="fa fa-reply"></span>
                </a>
            </div>
        </div>
    </div>
    <div class="card-block p-3">
        @using (Html.BeginForm("Chitiet", "tour_nguoidi", FormMethod.Post))
        {
            <p>ViewBag.choose</p>
            <div class="form-inline">
                @* <p>@ViewBag.choose</p>*@
                <label class="mr-3">Chọn tour: </label>
                <select class="form-control mr-3" name="selectedValue">

                    <option selected value="0">Select tour</option>
                    @{
                        foreach (var e in ViewBag.listTour)
                        {
                            <option selected value="@e.tour_id">@e.tour_ten</option>
                        }
                    }

                </select>

                <button class="btn btn-sm btn-success mr-3">Xem</button>
            </div>
        }
        <table class="table table-bordered table-hover table-striped w-100 mt-3">
            <tr>
                <th>#</th>
                <th>Đoàn đi</th>
                <th>Số khách</th>
                <th>Giá tour</th>
                <th>Doanh thu</th>
                <th>Tổng chi phí</th>
                <th>Lãi</th>
            </tr>
            @{
                    int i = 1;
                    int tdt = 0;
                    int tcp = 0;
                    foreach (var e in Model)
                    {
                        int zz = e.tongdanhthu - e.tongchiphi;
                        tdt += e.tongdanhthu;
                        tcp += e.tongchiphi;
                        <tr>
                            <td>@i</td>
                            <td>@e.tour</td>
                            <td>@e.sokhach</td>
                            <td>@e.giatour</td>
                            <td>@e.tongdanhthu | <a href="https://localhost:44341/tour_doan/Details/@e.idtour" >Chi tiết</a></td>
                            <td>@e.tongchiphi | <a href="https://localhost:44341/tour_doan/Chiphi/@e.idtour">Chi tiết</a></td>
                            <td>@zz</td>

                        </tr>
                        i = i + 1;
                    }
                    int lai = tdt - tcp;
                }
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Tổng</td>
                    <td>@tdt</td>
                    <td>@tcp</td>
                    <td>@lai</td>

                </tr>

        </table>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

projecttour/Views/tour_nguoidi/Create.cshtml
@model projecttour.Models.tour_nguoidi

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tour_nguoidi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nguoidi_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nguoidi_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nguoidi_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.doan_id, "doan_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("doan_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doan_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nguoidi_dsnhanvien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nguoidi_dsnhanvien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nguoidi_dsnhanvien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nguoidi_dskhachhang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nguoidi_dskhachhang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nguoidi_dskhachhang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

projecttour/Views/tour_nguoidi/Delete.cshtml
@model projecttour.Models.tour_nguoidi

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tour_nguoidi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nguoidi_dsnhanvien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nguoidi_dsnhanvien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nguoidi_dskhachhang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nguoidi_dskhachhang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tour_doan.doan_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tour_doan.doan_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

projecttour/Views/tour_nguoidi/Details.cshtml
@model projecttour.Models.tour_nguoidi

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tour_nguoidi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nguoidi_dsnhanvien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nguoidi_dsnhanvien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nguoidi_dskhachhang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nguoidi_dskhachhang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tour_doan.doan_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tour_doan.doan_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.nguoidi_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

projecttour/Views/tour_nguoidi/Index.cshtml
@model IEnumerable<projecttour.Controllers.tour_nguoidiController.thongke>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card w-100">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6 text-danger text-uppercase">
                <strong>Thống kê Tour</strong>
            </div>
        </div>
    </div>
    <div class="card-block p-3">
        <table class="table table-bordered table-hover table-striped w-100">
            <tr>
                <th>
                    #
                </th>
                <th>
                    Tour
                </th>
                <th>
                    Tổng số đoàn đi
                </th>
                <th>
                    Tổng doanh thu
                </th>
                <th>
                    Tổng chi phí
                </th>
                <th>
                    Lãi
                </th>
                <th class="text-center">Chức năng</th>
            </tr>

            @{
                int i = 1;
                foreach (var item in Model)
                {
                    int z = item.tongdanhthu - item.tongchiphi;
                    <tr>
                        <td>
                            @i
                        </td>
                        <td>
                            @item.tour
                        </td>
                        <td>
                            @item.tongdoandi
                        </td>
                        <td>
                            @item.tongdanhthu
                        </td>
                        <td>
                            @item.tongchiphi
                        </td>
                        <td>
                            @z
                        </td>
                        <td class="text-center">
                            <a href="@Url.Action("Chitiet",new { id = item.idtour })" class="btn btn-sm btn-success" data-toggle="tooltip" title="Xem">
                                <span class="fa fa-book-open"></span>
                            </a>
                        </td>
                    </tr>
                    i = i + 1;
                }
            }

        </table>
    </div>
</div>